mongodb/awscdk-resources-mongodbatlas

test/l3-resources/atlas-private-endpoint/index.test.ts
_Jira ticket:_ [INTMDB-712](https://jira.mongodb.org/browse/INTMDB-712)
Added unit tests for atlas-private-endpoint L3 construct
expected)
=> [INTMDB-712]: Add unit tests for atlas-private-endpoint l3

.projen/deps.json, .projen/tasks.json, .projenrc.js, API.md, package.json, src/index.ts, src/l3-resources/atlas-basic-private-endpoint/index.ts, src/l3-resources/atlas-basic-private-endpoint/integ.default.ts, src/l3-resources/atlas-basic/index.ts, src/l3-resources/common/props.ts, src/l3-resources/encryption-at-rest-express/index.ts, test/l2-resources/encryption-at-rest/index.test.ts, test/l2-resources/third-party-integration/index.test.ts, test/l3-resources/atlas-basic/index.test.ts, test/l3-resources/atlas-private-endpoint/index.test.ts, test/l3-resources/encryption-at-rest-express/index.test.ts, yarn.lock
_Jira ticket:_ [INTMDB-716](https://jira.mongodb.org/browse/INTMDB-716)
1. Refactored code for L3 constructs to use common properties to remove ambiguity.
2. Updated index.ts to export constructs and properties for better usage.
3. Removed references to @mongodbatlas-awscdk/atlas-basic
Testing steps:
1. Tested package locally by exporting .tgz file from dist/js and imported in a test CDK app to deploy stack in AWS
2. Published test package to NPM and imported in a test CDK app to deploy stack in AWS
Example usage of new package:
```
import * as en from "awscdk-resources-mongodbatlas";
// L2 - ThirdPartyIntegration (Datadog)
const datadogProps: en.DatadogIntegrationProps = {
apiKey: '...',
region: en.DatadogRegion.US,
projectId: '....'
}
new en.DatadogIntegration(this, 'TPI-dd', …
```
=> Refactor L3 construct props and index.ts

examples/README.md
doc bug fix similar to customer issue highlighted in https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/498
Link to any related issue(s): https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/498
expected)
=> Update AWS CDK README.md

.github/workflows/release.yml, .projenrc.js
_Jira ticket:_ INTMDB-762
This PR adds a GitHub action to automate the CDK release process: this action was **"inspired"** by the action used in CDKTF ([release.yml](https://github.com/cdktf/cdktf-provider-mongodbatlas/blob/main/.github/workflows/release.yml))
expected)
=> INTMDB-762: [CFN-PI] Automate Release Process CDK

.github/workflows/release.yml
_Jira ticket:_ INTMDB-762
- Fixes #31:  Adds `GIT_USER_NAME` and `GIT_USER_EMAIL` to the `release_golang`
- Updates the release action to publish to GitHub Release (prerelease) as we need to push a new tag to the repository
expected)
=> INTMDB-762: Publishing v1.0.1 to GitHub Go Module Repository failed

API.md, README.md
_Jira ticket:_ INTMDB-787
expected)
=> INTMDB-787: [CFN-PI] Add status badges to repository

API.md, README.md
_Jira ticket:_ INTMDB-799
This is a follow-up of https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/544
expected)
=> INTMDB-799: [CFN-PI] Update the Profile examples to include quote

API.md, src/index.ts, src/l1-resources/cloud-backup-snapshot/index.ts, src/l1-resources/serverless-instance/index.ts, src/l1-resources/x509-authentication-database-user/index.ts, test/l1-resources/cloud-backup-snapshot/index.test.ts, test/l1-resources/serverless-instance/index.test.ts
Refreshed changes on ServerlessInstance x509 CloudBuckupSnapshot
_Jira ticket: https://jira.mongodb.org/browse/INTMDB-700
expected)
=> Feature/INTMDB 700 ServerlessInstance x509 CloudBuckupSnapshot

API.md, src/l1-resources/trigger/index.ts
updated CDK Tiregger resource to reflect the changes of https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/607
Link to any related issue(s): [HELP-47378](https://jira.mongodb.org/browse/HELP-47378)
expected)
=> INTMDB-870: Fixed trigger resource 

API.md, src/l1-resources/clusters/index.ts
Cluster CDK was updated for:
- https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/600
- https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/611
_Jira ticket:
- [INTMDB-862](https://jira.mongodb.org/browse/INTMDB-862)
- [INTMDB-905)](https://jira.mongodb.org/browse/INTMDB-905)
expected)
=> INTMDB-905: Refreshed CDK for cluster 

API.md, src/l1-resources/cloud-backup-schedule/index.ts
Refreshed Cloud Buckup Schedule resource for https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/584
expected)
=> INTMDB-826: Refreshed Cloud Buckup Schedule

API.md, README.md
This PR adds https://www.mongodb.com/developer/products/atlas/deploy-mongodb-atlas-aws-cdk-typescript/ to the README
expected)
=> Update README.md to include new CDK guide

.github/workflows/pull-request-lint.yml
=> fix: update pull-request-lint.yml to remove pull_request and keep only pull_request_target

API.md, src/l1-resources/trigger/index.ts
Added project property to trigger resource
_Jira ticket:_ [INTMDB-947](https://jira.mongodb.org/browse/INTMDB-947)
expected)
=> feat: HELP-48343 added project propertie to trigger

API.md, src/index.ts, src/l1-resources/clusters/index.ts
Updated Cluster CDK for:
https://jira.mongodb.org/browse/INTMDB-818
https://jira.mongodb.org/browse/INTMDB-947
expected)
=> feat: INTMDB-818 INTMDB-947 update cluster CDK

API.md, src/l1-resources/project/index.ts
Update Project resource for [631](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/631)
_Jira ticket: [INTMDB-954](https://jira.mongodb.org/browse/INTMDB-954)
- Adding IsExtendedStorageSizesEnabled property in the project settings API.
- Added missing descriptions for the Properties of Project Resource
expected)
=> feat: intmdb 954 phase 2 project updates

.github/workflows/issues.yml
Follow up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1422
expected)
=> fix: update issue.yml to use issue number as Ticket title

.github/workflows/issues.yml
_Jira ticket:_ INTMDB-1190
Follow-up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1526
expected)
=> chore: INTMDB-1190: Update message added to github issue in the automation to create Jira ticket

examples/README.md
Fixes some relative links in `examples/README.md`.
expected)
=> doc: fix example README relative links

API.md, examples/l1-resources/cloud-backup-restore-jobs.ts, examples/mern-cdk-ci-cd/mern/server/package-lock.json, src/index.ts, src/l1-resources/cloud-backup-restore-jobs/index.ts, test/l1-resources/cloud-backup-restore-jobs/index.test.ts
Cloud Backup Restore Job resource was updated to reflect the changes on the next pull requests:
[640](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/640)
[661](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/661)
[759](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/759)
expected)
=> feat!: updated cloud buckup restore job and tests

API.md, examples/l1-resources/cloud-backup-snapshot.ts, src/index.ts, src/l1-resources/cloud-backup-snapshot/index.ts, test/l1-resources/cloud-backup-snapshot/index.test.ts
Updated Cloud Backup snapshot to reflect changes of [798](https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/798)
_Jira ticket:_ [INTMDB-1175](https://jira.mongodb.org/browse/INTMDB-1175)
expected)
=> fix!: INTMDB-1175 fixed cloud Backup snapshot primary identifier

.projen/tasks.json, .projenrc.js
_Jira ticket:_ [INTMDB-1255](https://jira.mongodb.org/browse/INTMDB-1255)
The CDK release is failing with the error: [this branch is configured to only publish v1 releases](https://github.com/mongodb/awscdk-resources-mongodbatlas/actions/runs/6762528093/job/18378590506#step:7:15). This PR fixes this error.
expected)
=> fix: this branch is configured to only publish v1 releases

.github/workflows/release.yml
This PR updates the action to release GitHub Release that are not pre-release
expected)
=> fix: the release Action is creating pre-release version

examples/mern-cdk-ci-cd/mern/client/package-lock.json, examples/mern-cdk-ci-cd/mern/client/package.json
Updates nth-check to 2.1.1.
Jira ticket: [INTMDB-1310](https://jira.mongodb.org/browse/INTMDB-1310)
expected)
=> fix: Updates nth-check to 2.1.1

RELEASING.md
Updates release doc.
Jira ticket: [INTMDB-1311](https://jira.mongodb.org/browse/INTMDB-1311)
expected)
=> chore: Updates release doc

.github/workflows/issues.yml
This PR removes the Assignee from the github action so that the created JIRA ticket is not assigned to a user.
expected)
=> fix: Removes Assignee from issues.yml

.github/workflows/issues.yml
_Jira ticket:_ CLOUDP-215192
expected)
=> chore: CLOUDP-215192 - Update Automation That Creates Github Issues To Create CLOUDP rather than INTMDB

.github/workflows/issues.yml
=> chore: Update issues.yml

.github/workflows/issues.yml
_Jira ticket:_ [CLOUDP-222765](https://jira.mongodb.org/browse/CLOUDP-222789)
The Jira automation was missing a check to create a ticket only when the GitHub issue was opened 
expected)
=> chore: fix a bug with the JIRA ticket automation

examples/l3-resources/atlas-serverless-basic.ts, src/l3-resources/atlas-serverless-basic/index.ts
_Jira ticket:_ CLOUDP-227532, CLOUDP-227575
Based on customer feedback, this PR updates/fixes a couple of issues with our L1 atlas-serverless and its related L3 resource:
* name properties: exposing name properties in the example and remove the _randomness_ logic in case of default values
* regionName: improve the L3 example by specifying the `regionName` field
Link to any related issue(s): https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/208, https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/209
Tested example and successfully worked.
_using a custom name_
_using a custom project name and its related custom serverless instance name_
expected)
=> fix: Updates atlas-serverless-basic example.

src/l3-resources/atlas-bootstrap/index.ts
As described in the attached issue, we don't need to set any account condition. In fact, when creating the `IAM execution role` through the other provided ways we don't specify it already.
_Jira ticket:_ CLOUDP-227526
Link to any related issue(s):  https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/207
expected)
=> fix: Updates policy in atlas-bootstrap.

RELEASING.md
_Jira ticket:_ CLOUDP-230543
expected)
=> doc: Adds additional considerations for running maven publishing manually

API.md, examples/l1-resources/stream-connection-cluster.ts, examples/l1-resources/stream-connection-sample.ts, examples/l1-resources/stream-connection.ts, scripts/cdk.sh, scripts/rename_in_file.py, scripts/rename_in_file_test.py, src/l1-resources/stream-connection/index.ts, test/l1-resources/stream-connection/index.test.ts
Adds support for stream-connection 'Sample' type
_Jira ticket:_ CLOUDP-234642
expected)
CREATE
DELETE
=> feat: Adds support for stream-connection 'Sample' type

API.md, src/l1-resources/stream-connection/README.md, src/l1-resources/stream-connection/index.ts, src/l1-resources/stream-instance/README.md, src/l1-resources/stream-instance/index.ts
Updates GA status for Atlas Stream resources
_Jira ticket:_ CLOUDP-237009
expected)
=> feat: Updates GA status for Atlas Stream resources

API.md, examples/l1-resources/project.ts, src/l1-resources/project/index.ts
Adds project tags
Link to any related issue(s): CLOUDP-245108
expected)
- CFN resource used
- `cdk deploy`
- `cdk deploy` (updating tags)
- `cdk destroy`
=> feat: Adds project tags

API.md, examples/l1-resources/auditing.ts, src/l1-resources/auditing/README.md, src/l1-resources/auditing/index.ts
Fixes Auditing resource
_Jira ticket:_ CLOUDP-246467
Link to any related issue(s):  https://github.com/mongodb/awscdk-resources-mongodbatlas/issues/265
expected)
=> fix: Fixes Auditing resource

API.md, README.md
Fixes some minor styles in README.md
Contribution from @svennergr in: https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/297
expected)
=> doc: Fixes some minor styles in README.md

API.md, src/l1-resources/global-cluster-config/index.ts
Updates GlobalClusterConfigProps description based on latest CFN resource
Link to any related issue(s): CLOUDP-256268
expected)
=> doc: Updates GlobalClusterConfigProps description based on latest CFN resource

.github/workflows/release.yml
chore: Enables NuGet publishing
_Jira ticket:_ CLOUDP-259045
expected)
=> chore: Enables NuGet publishing

RELEASING.md
Updates releasing doc
expected)
=> doc: Updates releasing doc

.github/workflows/release.yml
Changes signing app for NuGet
_Jira ticket:_ CLOUDP-262698
expected)
=> chore: Changes signing app for NuGet

.github/workflows/release.yml
Uses new signing app for NuGet
expected)
=> chore: Uses new signing app for NuGet

.github/workflows/code-health.yml, .gitignore, .npmignore, .projen/tasks.json, .projenrc.js, API.md, examples/l1-resources/alert-configuration.ts, examples/l1-resources/api-key.ts, examples/l1-resources/cloud-backup-restore-jobs.ts, examples/l1-resources/cloud-backup-schedule.ts, examples/l1-resources/cloud-backup-snapshot.ts, examples/l1-resources/cluster-outage-simulation.ts, examples/l1-resources/encryption-at-rest.ts, examples/l1-resources/federated-database-instance.ts, examples/l1-resources/federation-query-limit.ts, examples/l1-resources/global-cluster-config.ts, examples/l1-resources/ldap-configuration.ts, examples/l1-resources/ldap-verify.ts, examples/l1-resources/maintanance-windows.ts, examples/l1-resources/online-archive.ts, examples/l1-resources/organization.ts, examples/l1-resources/private-endpoint-v1-deprecated.ts, examples/l1-resources/private-endpoint.ts, examples/l1-resources/x509-authentication-db-user.ts, examples/l3-resources/encryption-at-rest-express.ts, scripts/check-examples.sh, src/l1-resources/alert-configuration/README.md, src/l1-resources/api-key/integ.default.ts, src/l3-resources/atlas-basic-private-endpoint/index.ts, test/l1-resources/api-key/index.test.ts
Ensures that TypeScript examples compile.   
Also the examples are fixed in this PR.
_Jira ticket:_ CLOUDP-251764
expected)
Example of fail logs:
=> chore: Ensures that examples compile

src/l1-resources/resource-policy/README.md
Updates the Public -> Private preview in docs for resource-policy
Link to any related issue(s): CLOUDP-277628
expected)
=> doc: Updates the Public -> Private preview in docs for resource-policy

src/l1-resources/resource-policy/README.md
_Jira ticket:_ [CLOUDP-#290399](https://jira.mongodb.org/browse/CLOUDP-290399) 
expected)
=> doc: Updates for Public Preview.

.github/workflows/code-health.yml, .github/workflows/package.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, examples/mern-cdk-ci-cd/mern/client/package-lock.json, examples/mern-cdk-ci-cd/mern/server/package-lock.json
- bump stuck dependency checks that are passing
expected)
=> chore: bump dependencies

API.md, examples/l1-resources/custom-db-role.ts, examples/l1-resources/database-user.ts, src/l1-resources/custom-db-role/index.ts, src/l1-resources/database-user/index.ts
- Adds optional `description` field to `CfnDatabaseUserProps` and update documentation of using empty string for custom db role
- CLOUDP-280706
- CLOUDP-288714
expected)
Deploy
Cloud DEV UI
Destroy
Deploy
Cloud-DEV UI
Destroy
=> feat: Adds optional `description` field to `CfnDatabaseUserProps` and update documentation of using empty string for custom db role
